[book]
title = "Example book"
authors = ["Prgh Traper"]
description = "The example book covers examples."

[rust]

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]

[output.html.search]
limit-results = 15
